config/routes.rb
Oncampuschef::Application.routes.draw do

  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }

  get "static_pages/why_us"
  get "static_pages/pricing"
  get "static_pages/what_we_do"
  get "static_pages/bbq"

  resources :charges, :except => [:show]
  resources :orders, :except => [:show]
  resources :barbecue_orders, :except => [:show]
  resources :barbecue_charges, :except => [:show]

 
  get "orders/vegetarian" => "orders#vegetarian"
  get "orders/food_picker" => "orders#food_picker"
  get "orders/test" => "orders#test"
  get "orders/test2" => "orders#test2"
  get "orders/quantity" => "orders#quantity"
  post "orders/new" => "orders#new"

  get "barbecue_orders/new"

  get "food_objects/menu"
 
  match '/chefs', to: 'static_pages#chefs', via: 'get'
  match '/profile', to: 'customers#show', via: 'get'
  match '/catering', to: 'catering_orders#new', via: 'get'

  get 'pages/index' => 'high_voltage/pages#show', id: 'index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def menu
  end

  def pricing
  end

  def order
  end

  def promotions
  end

  def faq
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/athlete.html.erb
<% provide(:title, 'Athlete') %>

<%= render 'shared/header' %>

<link rel="stylesheet" href="http://www.frontend.reklamor.com/fancybox/jquery.fancybox.css" media="screen">
<script src="http://www.frontend.reklamor.com/fancybox/jquery.fancybox.js"></script>

<div class="container" style="margin-top: 50px;">

    <p style="color:red;">*The Athlete Meal Plan is completely customizable. A single dish will consist of a protein, vegetable dish, and a side. Feel free to choose any combination of these dishes to create up to three meals of your choosing.  </p>

    <div class="row food-images">
        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/lemon-chicken.jpg">
                    <img class="img-responsive" alt="" src="/assets/lemon-chicken.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Baked Lemon Chicken</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">1. Baked Lemon Chicken (Protein)</h3>
                <p>Pair this lemon chicken recipe with crisp veggies and a side of rice for a delicious dinner.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/lemon-tilapia.jpg">
                    <img class="img-responsive" alt="" src="/assets/lemon-tilapia.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Baked Lemon Tilapia</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">2. Baked Lemon Tilapia (Protein)</h3>
                <p>These tilapia fillets are bathed in lemon juice and melted butter, seasoned with garlic and parsley, and baked to flaky perfection.</p>
        </div> <!-- col-6 / end -->
        
    </div> <!-- row / end -->

    <div class="row food-images">

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/salmon-honey.png">
                    <img class="img-responsive" alt="" src="/assets/salmon-honey.png" />
                    <div class='text-right'>
                        <small class='text-muted'>Honey Glazed Salmon</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">3. Honey Glazed Salmon (Protein)</h3>
                <p>Look no further—you’ve just found the first, last and only way you’ll ever want to eat salmon again. The sweet and tangy flavors blend beautifully.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/carrot-salad.jpg">
                    <img class="img-responsive" alt="" src="/assets/carrot-salad.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Morrocan Carrot Salad</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">4. Morrocan Carrot Salad (Veggies)</h3>
                <p>Sliced carrots are boiled then marinated with Moroccan spices, herbs, lemon juice, garlic and olive oil. Served warm or cold.</p>
        </div> <!-- col-6 / end -->

    </div> <!-- row / end -->

    <div class="row food-images">

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/squash-zuchinni.jpg">
                    <img class="img-responsive" alt="" src="/assets/squash-zuchinni.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Squash and Zucchini Medley</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">5. Squash and Zucchini Medley (Veggies)</h3>
                <p>Simple sauteed squash recipe combines zucchini and yellow summer squash for a colorful dish flavored with Italian seasoning.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/vegetable-stirfry.jpeg">
                    <img class="img-responsive" alt="" src="/assets/vegetable-stirfry.jpeg" />
                    <div class='text-right'>
                        <small class='text-muted'>Stir Fry Vegetables</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">6. Stir Fry Vegetables (Veggies)</h3>
                <p>While broccoli florets and chunks of red pepper give this dish plenty of color, it's the fresh gingerroot, garlic, soy sauce and sesame oil that round out the flavor of this dish.</p>
        </div> <!-- col-6 / end -->

    </div> <!-- row / end -->

    <div class="row food-images">

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/asparagus-honey.jpg">
                    <img class="img-responsive" alt="" src="/assets/asparagus-honey.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Baked Asparagus with Honey</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">7. Baked Asparagus with Honey (Veggies)</h3>
                <p>Just the slightest hint of honey adds the perfect amount of sweetness to this oven roasted asparagus dish.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/brown-rice.jpg">
                    <img class="img-responsive" alt="" src="/assets/brown-rice.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Brown Rice</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">8. Brown Rice (Side)</h3>
                <p>Rich in complex carbohydrates, this dish is a staple in any athlete's diet.</p>
        </div> <!-- col-6 / end -->

    </div> <!-- row / end -->

    <div class="row food-images">

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/whole-wheat-pasta.jpeg">
                    <img class="img-responsive" alt="" src="/assets/whole-wheat-pasta.jpeg" />
                    <div class='text-right'>
                        <small class='text-muted'>Whole Wheat Pasta</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">9. Whole Wheat Pasta (Side)</h3>
                <p>Rich in flavor and nutritional benefits. Let this tastey dish fuel your daily activities and workouts.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/quinoa.jpg">
                    <img class="img-responsive" alt="" src="/assets/quinoa.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Quinoa</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">10. Quinoa (Side)</h3>
                <p>High in protein and fiber, quinoa is not only versatile, it also tastes wonderful and has a nice crunch.</p>
        </div> <!-- col-6 / end -->

    </div> <!-- row / end -->
</div> <!-- container / end -->

</br>

<a href = "<%= new_athlete_path %>" class = "customer-order-button">
<button type="button" class="btn btn-info btn-lg center-block order-button">Order Now</button>
</a>

<script>
    $(document).ready(function(){
    //FANCYBOX
    //https://github.com/fancyapps/fancyBox
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });
    });
   
  
</script>

<%= render 'shared/footer' %>

app/views/static_pages/bbq.html.erb
<% provide(:title, 'BBQ Plan') %>
<%= render 'shared/header' %>

<style>
	body {
		background-color: #FDFDFD;
	}
</style>

<div class="container" style="margin-top: 3%; margin-bottom: 3%;">

	<h1>WeCook BBQ Plan</h1>
	<hr>

	<div class="row" style="margin-top: 2%;">
		<h3>This is what you get for a great BBQ:</h3>
		<ul>
			<li>Burgers - beef, chicken, or turkey</li>
			<li>Chicken Kabobs</li>
			<li>Hot dog - chicken, beef, or pork</li>
			<li>Grilled vegetables</li>
			<li>Cole slaw</li>
			<li>Corn</li>
		</ul>
		<p style="font-weight: bold;">* Buns, cheese, and condiments provided</p>
		<p style="font-weight: bold;">Customer to provide a grill, grilling accessories (tongs, skewers, etc.)</p>

		<h3>You will be given the option to specify the meat preference after your order has been placed.</h3>
	</div>

	<div class="row" style="margin-top: 5%;">
	<table class="table table-striped table-hover">
  		<thead>
  			<tr>
				<th colspan="7" class="text-center">Barbecue Packages</th>
  			</tr>
			<tr>
				<th>Package #</th>
				<th># of people served</th>
				<th>Chef hours</th>
				<th>Cost Per Person</th>
				<th>Total Cost</th>
			</tr>
  		</thead>
  		<tbody>
			<tr>
				<td>1</td>
				<td>50</td>
				<td>4</td>
				<td>$9.74</td>
				<td>$486.80</td>
			</tr>
			<tr>
				<td>2</td>
				<td>40</td>
				<td>4</td>
				<td>$10.52</td>
				<td>$420.80</td>
			</tr>
			<tr>
				<td>3</td>
				<td>30</td>
				<td>3</td>
				<td>$11.83</td>
				<td>$354.80</td>
			</tr>
			<tr>
				<td>4</td>
				<td>20</td>
				<td>3</td>
				<td>$14.44</td>
				<td>$288.80</td>
			</tr>
			<tr>
				<td>5</td>
				<td>10</td>
				<td>3</td>
				<td>$19.40</td>
				<td>$194.00</td>
			</tr>
  		</tbody>
	</table>
	</div>

	<div class="row" style="margin-top:4%;">
		<table class="table table-striped table-hover">
  		<thead>
  			<tr>
				<th colspan="7" class="text-center">ADD ON PREMIUM ITEMS</th>
  			</tr>
			<tr>
				<th>Control #</th>
				<th># of people served</th>
				<th>Shrimp</th>
				<th>Beef Kabob</th>
				<th>Lamb Kabob</th>
				<th>Meat balls- Chicken/Beef</th>
				<th>Veggie Burgers</th>
			</tr>
  		</thead>
  		<tbody>
			<tr>
				<td>1</td>
				<td>40</td>
				<td>$80</td>
				<td>$56</td>
				<td>$64</td>
				<td>$60</td>
				<td>$56</td>
			</tr>
			<tr>
				<td>2</td>
				<td>30</td>
				<td>$56</td>
				<td>$32</td>
				<td>$51</td>
				<td>$45</td>
				<td>$42</td>
			</tr>
			<tr>
				<td>3</td>
				<td>20</td>
				<td>$40</td>
				<td>$24</td>
				<td>$38</td>
				<td>$30</td>
				<td>$28</td>
			</tr>
			<tr>
				<td>4</td>
				<td>10</td>
				<td>$24</td>
				<td>$16</td>
				<td>$26</td>
				<td>$19</td>
				<td>$14</td>
			</tr>
  		</tbody>
	</table>
	</div>

	<h3>*You can add any of the above premium items to your order for the additional cost of selected items.</h3>

	<div class="row" style="margin-top: 4%;">
		<a href = "/barbecue_orders/new" class = "customer-order-button">
<button type="button" class="btn btn-info btn-lg center-block order-button">Order Now</button> </a>
	</div>

</div>


<%= render 'shared/footer' %>

app/views/static_pages/budget.html.erb
<% provide(:title, 'Budget') %>

<%= render 'shared/header' %>

<link rel="stylesheet" href="http://www.frontend.reklamor.com/fancybox/jquery.fancybox.css" media="screen">
<script src="http://www.frontend.reklamor.com/fancybox/jquery.fancybox.js"></script>

<div class="container" style="margin-top: 50px;">
    <div class="row food-images">
        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/pasta-asparagus.jpg">
                    <img class="img-responsive" alt="" src="/assets/pasta-asparagus.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Pasta with asparagus and French Onion</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">1. Pasta with asparagus and French Onion</h3>
                <p>Mix together spaghetti with asparagus and onion for a quick Italian meal that's sure to please.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/pork-quesadillas.jpg">
                    <img class="img-responsive" alt="" src="/assets/pork-quesadillas.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Barbecued Pork Quesadillas</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">2. Barbecued Pork Quesadillas</h3>
                <p>Sweet and tangy, these quesadillas get their flavor from the shredded barbeque pork and barbeque sauce.</p>
        </div> <!-- col-6 / end -->
        
    </div> <!-- row / end -->

    <div class="row food-images">

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/hamburger-onions.jpg">
                    <img class="img-responsive" alt="" src="/assets/hamburger-onions.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Hamburger with onion and mushrooms</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">3. Hamburger with onion and mushrooms</h3>
                <p>Spicy, cheesy, and tasty; this dish has it all.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/porkchops.jpg">
                    <img class="img-responsive" alt="" src="/assets/porkchops.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Pork Chops</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">4. Pork Chops</h3>
                <p>Get big bone-in flavor with these high quality pork chops</p>
        </div> <!-- col-6 / end -->

    </div> <!-- row / end -->
</div> <!-- container / end -->

</br>

<a href = "<%= new_budget_path %>" class = "customer-order-button">
<button type="button" class="btn btn-info btn-lg center-block order-button">Order Now</button>
</a>


<script>
    $(document).ready(function(){
    //FANCYBOX
    //https://github.com/fancyapps/fancyBox
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });
    });
   
  
</script>

<%= render 'shared/footer' %>

app/views/static_pages/pricing.html.erb
<% provide(:title, 'Pricing') %>
<%= render 'shared/header' %>

<style>
	body {
		background-color: #FDFDFD;
	}
</style>

<div class="container" style="margin-bottom: 3%;">
<div class="row" style="margin-top: 3%;">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<h1 class="text-center">Pricing</h1>
		<hr>
		<h3 class="text-center" style="color: gray;">Cost &amp; Convenience, Health &amp; Hygiene, or Taste &amp; Temptation</h3>
	</div>
	<div class="col-md-4"></div>
</div>

<div class="row" style="margin-top: 3%;">
	<p class="text-center">
	WeCook is an affordable lifestyle choice. We aim to provide a service that can be used regularly so that anyone can eat healthy, delicious, homemade meals on a daily basis made by your very own personal chef. The more meals you order in an appointment, the less the price is per meal. Find people to order in a group and watch as you are magically spending less than $9 a meal for your very own personal chef!</p>


</div>

<div class="row" style="margin-top: 3%;">
		<div class="col-md-2"></div>
			<div class="col-md-8">
			<h2 class="text-center">Number of Meals: </h2>
			<p class="text-center" style="margin-bottom: 5%;">Cost is dependent on total number of meals. Drag the slider to increase the number of total meals.</p>
			<input id="ex6" type="text" data-slider-min="8" data-slider-max="30" data-slider-step="2" data-slider-value="8"/&t

			<span id="ex6CurrentSliderValLabel"><h2 class="text-center">Total Cost: <span id="ex6SliderVal">$102.64</span></h2></span>
			<span id="ex6CurrentSliderValLabel"><h2 class="text-center">Price per meal: <span id="ex6SliderVal2">$12.83</span></h2></span>

			<h2 class="text-center" style="margin-top: 5%;">For two weeks we are giving you 10% off on all of your orders over 8 meals. Just use the promo code: healthy123. Apply the discount to the prices shown above.</h2>

			<script>
				// With JQuery
				$("#ex6").slider();
				$("#ex6").on("slide", function(slideEvt) {
					if (slideEvt.value == 8) {
						$("#ex6SliderVal").text("$102.64");
						$("#ex6SliderVal2").text("$12.83");
					} else if (slideEvt.value == 10) {
						$("#ex6SliderVal").text("$125.70");
						$("#ex6SliderVal2").text("$12.57");
					} else if (slideEvt.value == 12) {
						$("#ex6SliderVal").text("$147.72");
						$("#ex6SliderVal2").text("$12.31");
					} else if (slideEvt.value == 14) {
						$("#ex6SliderVal").text("$168.70");
						$("#ex6SliderVal2").text("$12.05");
					} else if (slideEvt.value == 16) {
						$("#ex6SliderVal").text("$188.64");
						$("#ex6SliderVal2").text("$11.79");
					} else if (slideEvt.value == 18) {
						$("#ex6SliderVal").text("$207.54");
						$("#ex6SliderVal2").text("$11.53");
					} else if (slideEvt.value == 20) {
						$("#ex6SliderVal").text("$225.40");
						$("#ex6SliderVal2").text("$11.27");
					} else if (slideEvt.value == 22) {
						$("#ex6SliderVal").text("$242.22");
						$("#ex6SliderVal2").text("$11.01");
					} else if (slideEvt.value == 24) {
						$("#ex6SliderVal").text("$258.00");
						$("#ex6SliderVal2").text("$10.75");
					} else if (slideEvt.value == 26) {
						$("#ex6SliderVal").text("$272.74");
						$("#ex6SliderVal2").text("$10.49");
					} else if (slideEvt.value == 28) {
						$("#ex6SliderVal").text("$286.44");
						$("#ex6SliderVal2").text("$10.23");
					} else if (slideEvt.value == 30) {
						$("#ex6SliderVal").text("$299.10");
						$("#ex6SliderVal2").text("$9.97");
					}
				});
			</script>
			</div>

		<div class="col-md-2"></div>
</div>
</div>


<%= render 'shared/footer' %>

app/views/static_pages/vegetarian.html.erb
<% provide(:title, 'Vegetarian') %>

<%= render 'shared/header' %>

<link rel="stylesheet" href="http://www.frontend.reklamor.com/fancybox/jquery.fancybox.css" media="screen">
<script src="http://www.frontend.reklamor.com/fancybox/jquery.fancybox.js"></script>

<div class="container" style="margin-top: 50px;">
    <div class="row food-images">
        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/carbonara.jpg">
                    <img class="img-responsive" alt="" src="/assets/carbonara.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Creamy Avocado Carbonara</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">1. Creamy Avocado Carbonara</h3>
                <p>The beloved spaghetti carbonara dish topped with a creamy and delicious avocado sauce.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/pad_thai.jpg">
                    <img class="img-responsive" alt="" src="/assets/pad_thai.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Vegetarian Pad Thai</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">2. Vegetarian Pad Thai</h3>
                <p>Served with Green Onions and Cilantro sprinkled over the top, with a lime wedge squeezed over it all for more citrus-y flavor.</p>
        </div> <!-- col-6 / end -->
        
    </div> <!-- row / end -->

    <div class="row food-images">

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/vegan_padthai.jpg">
                    <img class="img-responsive" alt="" src="/assets/vegan_padthai.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Vegan Pad Thai</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">3. Vegan Pad Thai</h3>
                <p>Stir Fry noodles sprinkled with peanuts, bean sprouts, and raw green onions. Served with a slice of lime.</p>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/tofu_curry.jpeg">
                    <img class="img-responsive" alt="" src="/assets/tofu_curry.jpeg" />
                    <div class='text-right'>
                        <small class='text-muted'>Tofu Squash Curry</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">4. Tofu Squash Curry</h3>
                <p>Lightly browned tofu soaked in curry paste, steamed, then served with a mix of vegetables</p>
        </div> <!-- col-6 / end -->

    </div> <!-- row / end -->

    <div class="row food-images">

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <a class="thumbnail fancybox" rel="ligthbox" href="/assets/kale_pasta.jpg">
                    <img class="img-responsive" alt="" src="/assets/kale_pasta.jpg" />
                    <div class='text-right'>
                        <small class='text-muted'>Vegan Spicy Creamy Kale Pasta</small>
                    </div> <!-- text-right / end -->
                </a>
        </div> <!-- col-6 / end -->

        <div class='col-sm-6 col-xs-6 col-md-3 col-lg-3'>
                <h3 style="font-weight: bold;">5. Vegan Spicy Creamy Kale Pasta</h3>
                <p>Perfectly cooked kale pasta tossed with cream sauce, and sprinkled with a dash of chile powder for some color.</p>
        </div> <!-- col-6 / end -->

    </div> <!-- row / end -->
</div> <!-- container / end -->

</br>

<a href = "<%= new_vegetarian_path %>" class = "customer-order-button">
<button type="button" class="btn btn-info btn-lg center-block order-button">Order Now</button>
</a>

<script>
    $(document).ready(function(){
    //FANCYBOX
    //https://github.com/fancyapps/fancyBox
        $(".fancybox").fancybox({
            openEffect: "none",
            closeEffect: "none"
        });
    });
   
  
</script>

<%= render 'shared/footer' %>