config/routes.rb
Oncampuschef::Application.routes.draw do

  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }

  get "static_pages/why_us"
  get "static_pages/pricing"
  get "static_pages/what_we_do"
  get "static_pages/bbq"

  resources :charges, :except => [:show]
  resources :orders, :except => [:show]
  resources :barbecue_orders, :except => [:show]
  resources :barbecue_charges, :except => [:show]

 
  get "orders/vegetarian" => "orders#vegetarian"
  get "orders/food_picker" => "orders#food_picker"
  get "orders/test" => "orders#test"
  get "orders/test2" => "orders#test2"
  get "orders/quantity" => "orders#quantity"
  post "orders/new" => "orders#new"

  get "barbecue_orders/new"

  get "food_objects/menu"
 
  match '/chefs', to: 'static_pages#chefs', via: 'get'
  match '/profile', to: 'customers#show', via: 'get'
  match '/catering', to: 'catering_orders#new', via: 'get'

  get 'pages/index' => 'high_voltage/pages#show', id: 'index'

end

app/views/shared/_athlete.html.erb
<p>
	                    	 You can customize up to three meals, choosing from a protein, a veggie, and a side dish for each meal. For example, an order for this meal plan would look like: (1, 4, 10), (2, 7, 8), and (3, 5, 9 ). Please follow this format when entering your order.
						 	</p>

						 	<ol>
						 	 <li>Baked Lemon Chicken (Protein)</li>
						     <li>Baked Lemon Tilapia (Protein)</li>
						     <li>Honey Glazed Salmon (Protein)</li>
						     <li>Morrocan Carrot Salad (Veggies)</li>
						     <li>Squash and Zucchini Medley (Veggies) </li>
						     <li>Stir Fry Vegetables (Veggies)</li>
						     <li>Baked Asparagus with honey (Veggies)</li>
						     <li>Brown Rice (Side)</li>
						     <li>Whole Wheat Pasta (Side)</li>
						     <li>Quinoa (Side)</li>

						 	</ol>

app/views/shared/_budget.html.erb
<p>
						     Please enter the number of up to three food items, separated by commas, from the budget menu:
						 	</p>

						 	<ol>
						 	 <li>Pasta with asparagus and French Onion</li>
						     <li>Barbecued Pork Quesadillas</li>
						     <li>Hamburger with onion and mushrooms</li>
						     <li>Pork Chops</li>
						 	</ol>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		  <% object.errors.full_messages.each do |msg| %>
		  	<li>* <%= msg %></li>
		  <% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="contact" class="footer" style = "margin-bottom: -5px; margin-top: 0px;">

      <div class="container">    
        <div class="row">
          <div class="col-lg-12">
            <div class="col-sm-4 col-md-4"></div>
            <div class="col-sm-4 col-md-4 text-center">
              <div class="footer-logo">
                <h2>WeCook</h2>
                <p>(703) 894-7630</p>
                <br>
                <p class="muted">© 2014 WeCook Inc.</p>
              </div>
            </div>
            <div class="col-sm-4 col-md-4"></div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12 text-center">
            <a class="icon" href="https://twitter.com/chefumd" target="_blank"><i class="fa fa-twitter"></i></a>
            <a class="icon" href="https://www.facebook.com/pages/On-Campus-Chef/1506580929590404?ref=aymt_homepage_panel" target="_blank"><i class="fa fa-facebook"></i></a>
          </div>
        </div>
      </div>

</footer>

app/views/shared/_header.html.erb
<div class = "navbar navbar-inverse navbar-static-top navigation">
	<div class = "container">
		<div class = "navbar-header">
			<a href= "<%= root_path %>" class = "navbar-brand home-link" style=""><img class="img-responsive" src="/assets/WeCook_official_logo.png"/></a>

			<button class = "navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
				<span class = "icon-bar"></span>
			</button>
		</div>
		<div class = "collapse navbar-collapse navHeaderCollapse">
			<ul class = "nav navbar-nav navbar-right">
				<li><a href = "/food_objects/menu">Menu</a></li>
				 <% if signed_in? %>

                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="/profile">Profile</a></li>
                        <li><%= link_to('Sign Out', destroy_customer_session_path, :method => :delete) %></li>
                      </ul>
                    </li>
                <% else %>
                 <li><%= link_to('Login', new_customer_session_path) %></li>
                <% end %>
				<li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                         <li class=""><a href="/static_pages/why_us">Why Us</a></li>
                         <li><a href = "/static_pages/what_we_do">What We Do</a></li>
                         <li><a href = "/static_pages/pricing">Pricing</a></li>
                      </ul>
                </li>
				<li><a href = "/static_pages/bbq">WeCook Out</a></li>
			</ul>
		</div>
	</div>
</div>

app/views/shared/_healthyliving.html.erb
<p>
						     Please enter the number of up to three food items, separated by commas, from the healthy living menu:
						 	</p>

						 	<ol>
						 	 <li>Deconstructed Sushi Roll</li>
						     <li>Tangy Chicken Trail Mix</li>
						     <li>Hawaiian Stir Fry</li>
						     <li>Healthy BBQ Stir Fry</li>
						     <li>Old Bay Turkey Burger </li>
						     <li>Pecan Crusted Tilapia</li>

						 	</ol>

app/views/shared/_homestyle.html.erb
<p>
						     Please enter the number of up to three food items, separated by commas, from the home style menu. For the Tex Mex dish specify the choice of meat. For example an order could look like 1, 2, 6 chicken:
						 	</p>

						 	<ol>
						 	 <li>BBQ Chicken/Steak Quesadilla</li>
						     <li>Southern Mac and Cheese</li>
						     <li>Spicy Chicken Casserole with assorted vegetables</li>
						     <li>Chipotle Pork Chops</li>
						     <li>Shepherd's Pie</li>
						     <li>Tex Mex (Chicken, Steak, Vegetarian)</li>

						 	</ol>

app/views/shared/_preloader.html.erb
<div class="preloader">
       <div class="spinner">
          <div class="bounce1"></div>
          <div class="bounce2"></div>
          <div class="bounce3"></div>
        </div>
    </div>

app/views/shared/_slicknavbar.html.erb
    <!-- NAVBAR
    ================================================== -->

    <div class="navbar-wrapper cbp-af-header">
      <div class="container">

        <!-- Fixed navbar -->
        <div class="navbar cbp-af-inner" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand scroll" href="<%= root_path %>"><img class="official-logo" src="/assets/WeCook_official_logo.png"/></a>
              <!--<h1><a class="navbar-brand" href="<%= root_path %>">WeCook</a></h1>-->
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav pull-right">
                <li class=""><a href="/food_objects/menu">Menu</a></li>
                <% if signed_in? %>

                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="/profile">Profile</a></li>
                        <li><%= link_to('Sign Out', destroy_customer_session_path, :method => :delete) %></li>
                      </ul>
                    </li>
                <% else %>
                 <li><%= link_to('Login', new_customer_session_path) %></li>
                <% end %>

                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                         <li class=""><a href="/static_pages/why_us">Why Us</a></li>
                         <li><a href = "/static_pages/what_we_do">What We Do</a></li>
                         <li><a href = "/static_pages/pricing">Pricing</a></li>
                      </ul>
                </li>
                <li><a href = "/static_pages/bbq">WeCook Out</a></li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>

app/views/shared/_step1.html.erb
<div class="col-md-4">
</div>
<div class="col-md-4">
<div class="center-block">

<h1 class="center-text">
Select Number of Meals
</h1>
<div class = "slid">
<input id="ex8" data-slider-id='ex1Slider' type="text" data-slider-min="6" data-slider-max="24" data-slider-step="2" data-slider-value="6"/>
<script>
$("#ex8").slider({tooltip: 'hide'})
$("#ex8").on("slide", function(slideEvt) {
$("#ex6SliderVal").text(slideEvt.value);
});
</script>
</div>
<div>
<h1 class = "center-text" id="ex6SliderVal">6</h1>
</div>
<div>
<a href="#" class="btn btn-block btn-lg btn-primary" id = "btn1"> Next <i class="fa fa-arrow-right order-arrow"></i></a>
<script>
$("#btn1").on('click', function (e) {
$("#step1").hide();
$("#step2").show();
});
</script>
</div>
</div>
<div class="col-md-4">
</div>
</div>










<div class="first block1 show">
		    <label for="firstname">Firstname:</label>
		    <input type="text" name="firstname" data-parsley-group="block1" required/>

		    <label for="lastname">Lastname:</label>
		    <input type="text" name="lastname" data-parsley-group="block1" required />
		    <span class="next btn btn-info" data-current-block="1" data-next-block="2">Next ></span>
</div>

app/views/shared/_vegetarian.html.erb
<p>
						     Please enter the number of up to three food items, separated by commas, from the vegetarian menu.
						 	</p>

						 	<ol>
						 	 <li>Creamy Avocado Carbonara</li>
						     <li>Vegetarian Pad Thai</li>
						     <li>Vegan Pad Thai</li>
						     <li>Tofu Squash Curry</li>
						     <li>Vegan Spicy Creamy Kale Pasta</li>

						 	</ol>