config/routes.rb
Oncampuschef::Application.routes.draw do

  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }

  get "static_pages/why_us"
  get "static_pages/pricing"
  get "static_pages/what_we_do"
  get "static_pages/bbq"

  resources :charges, :except => [:show]
  resources :orders, :except => [:show]
  resources :barbecue_orders, :except => [:show]
  resources :barbecue_charges, :except => [:show]

 
  get "orders/vegetarian" => "orders#vegetarian"
  get "orders/food_picker" => "orders#food_picker"
  get "orders/test" => "orders#test"
  get "orders/test2" => "orders#test2"
  get "orders/quantity" => "orders#quantity"
  post "orders/new" => "orders#new"

  get "barbecue_orders/new"

  get "food_objects/menu"
 
  match '/chefs', to: 'static_pages#chefs', via: 'get'
  match '/profile', to: 'customers#show', via: 'get'
  match '/catering', to: 'catering_orders#new', via: 'get'

  get 'pages/index' => 'high_voltage/pages#show', id: 'index'

end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :customer
	serialize :food_items, Array
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	
	before_filter :authenticate_customer!

	def index
	end

	def quantity

	end

	def new
		@quantity = params[:quantity]
		@order = Order.new() # without the parantheses! (order_params)
		@order.num_meals = @quantity
		@order.customer_id = current_customer.id
		@order.save

		#determine how many meals the customer can select
		if @quantity.to_i == 8 || @quantity.to_i == 10 || @quantity.to_i == 12
			@howMany = 3
		elsif @quantity.to_i == 14 || @quantity.to_i == 16
			@howMany = 4
		else
			@howMany = 5 # this shouldn't be the default case
		end

		@food_items = FoodObject.all
		#@food_items = FoodObject.find(:all, :order => "id desc", :limit => 6)
	end

	def create
		@food_items = FoodObject.all
		@amount = 0

		@new_order = Order.where("customer_id = #{current_customer.id}").first(:order => 'id DESC')
		@new_order.status = "unpaid"
		@new_order.food_items = []
		params.each_pair{|k,v|
			if FoodObject.exists?(name: v)
				@new_order.food_items.push(v)
				@amount = @amount + 1
			elsif k == "contact_info"
				@new_order.contact_info = v
			elsif k == "address"
				@new_order.address = v
			elsif k == "chef_date"
				@new_order.appointment_date = v
			elsif k == "grocery_date"
				@new_order.grocery_date = v
			elsif k == "promocode"
				@new_order.promo_code = v
			elsif k == "food_restrictions"
				@new_order.food_restrictions = v
			end
		}

		#@new_order.customer_id = current_customer.id

		# error checking #
		if @new_order.num_meals.to_i == 8 || @new_order.num_meals.to_i == 10 || @new_order.num_meals.to_i == 12
			@howMany = 3
		elsif @new_order.num_meals.to_i == 14 || @new_order.num_meals.to_i == 16
			@howMany = 4
		else
			@howMany = 5
		end

		# end error check #

		respond_to do |format|
			if @amount <= 0 || @amount > @howMany
				flash[:error] = "Error: Must Order Up To #{ @howMany } Meals!"
				format.html { render action: 'new' }
			else
				if @new_order.save
					format.html { redirect_to '/charges/new' }
	        		format.js
				else
				  format.html { render action: 'new' }
				        
				  # added: not working after adding redirects
				  format.js   { render json: @new_order.errors, status: :unprocessable_entity }
				end
			end
		end
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/new.html.erb
<% provide(:title, 'Order') %>

 <%= render 'shared/header' %>
    
<div class="container ms-checkout a">

        <% flash.each do |key, value| %>
            <h3 style="color: red;"><%= content_tag(:div, value, class: "alert alert-#{key}") %></h3>
        <% end %> 


<form id="example-advanced-form" action="<%=orders_path%>" method="POST">
    
    <!-- step 1: pick your meals -->

    <h3>Order</h3>
    <fieldset class="step1-order">
        <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

            <div class="row menu-checkout">
                <legend class="ms-legend-1">Select up to <%= @howMany %> meals</legend>
                
                    <div class="col-md-5 menu">
                        <% i = 1 %>
                        <% @food_items.each do |food| %>
                          <div class="menu-item">
                            <input type="checkbox" id="a" name="choice<%= i %>" value="<%= food.name %>"/>
                            <label for="a"><%= food.name %></label>
                          </div>
                         <% i = i + 1 %>
                        <% end %> 
                    </div>
                    
                
            </div>
            
            <%= javascript_tag do %>
              var max = <%= @howMany.to_i.to_json %>;
            <% end %>

            <script>
                function countChecked() {                             
                  var n = $("input:checked").length;                       

                  if (n == max)                                              
                  {                                                        
                     $(':checkbox:not(:checked)').prop('disabled', true);  
                  }                                                        
                  else                                                     
                  {                                                        
                     $(':checkbox:not(:checked)').prop('disabled', false); 
                  }                                                        
                }                                                                                              
                $(":checkbox").click(countChecked);       
            </script>
    </fieldset>
 
    <h3>Schedule</h3>
    <fieldset>
        <div class="row" style="margin-top: 1%;">
        <legend class="ms-legend-2">Select a date and time that you will be available</legend>
                    
                    <div class="col-md-8" style="margin-top: 5%;">
                        <h4>*please schedule chef appointment 3 days in advance</h4>
                        <h3 class="fs-title">Pick a time for your chef appointment, our hours of operation are from 9 AM - 10 PM</h3>
                        <div class="form-group" style="margin-top: 3%;">
                            <div class='input-group date' id='datetimepicker2'>
                            <input type="text" class="form-control required" name="chef_date" required />
                            <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-8">
                        <h4>*please schedule your grocery delivery up to 24 hours before the chef appointment -- note that PeaPod will deliver your groceries within a two hour timeframe from the time you select.</h4>
                        <h3 class="fs-title">Pick a time that you want your groceries delivered. We deliver from 7 AM - 10 PM</h3>
                        <div class="form-group" style="margin-top: 3%;">
                            <div class='input-group date' id='datetimepicker1'>
                            <input type="text" class="form-control required" name="grocery_date" required />
                            <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            </div>
                        </div>
                    </div>
                    
                <script type="text/javascript">
                    $(function () {
                        $('#datetimepicker1').datetimepicker({
                        sideBySide: true,
                        });
                    });

                    $(function () {
                        $('#datetimepicker2').datetimepicker({
                        sideBySide: true,
                        });
                    });
                </script>
        </div>
    </fieldset>
    
    <h3>Food Restrictions</h3>
    <fieldset>
        <div class="row" style="margin-top: 1%;">
        <legend class="ms-legend-2">Optionally specify any food restrictions</legend>
                    
                    <div class="col-md-8" style="margin-top: 5%;">
                        <h3 class="fs-title">If you have any food allergies or diet restrictions, please note them in the box below: </h3>
                        <textarea style="margin-top: 3%;" name="food_restrictions" rows="5" cols="50">
                            
                        </textarea>
                    </div>                 
        </div>
    </fieldset>

    <h3>Contact</h3>
    <fieldset>
        <legend class="ms-legend">Enter your phone number and address</legend>
        <div class="row shit">
                <div class="col-md-10" style="margin-left: 3%;">
                        <h2 class="fs-title">Enter Contact info</h2>
                        <h3 class="fs-subtitle" style="margin-bottom: 4%;">So that we can get your food to you!</h3>
                        <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">Address: </span>
                        <input type="text" class="form-control required" placeholder="100 Hungry Lane" aria-describedby="basic-addon1" name="address" data-parsley-group="block3" required />
                        </div>
                        <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">Phone</span>
                        <input type="text" class="form-control required" placeholder="555-555-5555" aria-describedby="basic-addon1" name="contact_info" data-parsley-group="block3" required>
                        </div>
                </div>
            </div>
    </fieldset>
    
    <!-- optional step for promo code -->
    <h3>Promo Code</h3>
    <fieldset>
        <legend class="ms-legend">Enter an optional promo code to receive a 10% discount!</legend>
        <div class="row shit">
                <div class="col-md-10" style="margin-left: 3%;">
                        <h3 class="fs-subtitle" style="margin-bottom: 4%;">If you're ordering more than 8 meals, enter the promo code: healthy123 to receive a 10% discount</h3>
                        <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">Promo code: </span>
                        <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon1" name="promocode" />
                        </div>

                        <input style="margin-top: 5%;" type="submit" class="btn btn-info submit" />
                </div>
            </div>
    </fieldset>
 
</form>

</div>

<script>

var form = $("#example-advanced-form").show();
 
form.steps({
    headerTag: "h3",
    bodyTag: "fieldset",
    transitionEffect: "slideLeft",
    onStepChanging: function (event, currentIndex, newIndex)
    {
        // Allways allow previous action even if the current form is not valid!
        if (currentIndex > newIndex)
        {
            return true;
        }
        // Forbid next action on "Warning" step if the user is to young
        if (newIndex === 4 && Number($("#age-2").val()) < 18)
        {
            return false;
        }
        // Needed in some cases if the user went back (clean up)
        if (currentIndex < newIndex)
        {
            // To remove error styles
            form.find(".body:eq(" + newIndex + ") label.error").remove();
            form.find(".body:eq(" + newIndex + ") .error").removeClass("error");
        }
        form.validate().settings.ignore = ":disabled,:hidden";
        return form.valid();
    },
    onStepChanged: function (event, currentIndex, priorIndex)
    {
        // Used to skip the "Warning" step if the user is old enough.
        if (currentIndex === 4 && Number($("#age-2").val()) >= 18)
        {
            form.steps("next");
        }
        // Used to skip the "Warning" step if the user is old enough and wants to the previous step.
        if (currentIndex === 2 && priorIndex === 3)
        {
            form.steps("previous");
        }
    }
}).validate({
    errorPlacement: function errorPlacement(error, element) { element.before(error); },
    rules: {
        confirm: {
            equalTo: "#password-2"
        }
    }
});

</script>




    
 <%= render 'shared/footer' %>

app/views/orders/quantity.html.erb
<%= render 'shared/header' %>
<% provide(:title, 'Order') %>

<div class="container">
<form action="<%= new_order_path %>" method="POST">

<div class="jumbotron" style="margin-top: 10%; margin-bottom: 10%;">
	<legend class="ms-legend">Select how many meals you want</legend>
	<h2 class="text-center" style="margin-top: 3%; margin-bottom: 5%;">Pick up to 30 meals</h2>
	
	<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

			<input id="ex8" class="slider" data-slider-id='ex1Slider' type="text" data-slider-min="8" data-slider-max="30" data-slider-step="2" data-slider-value="8" name="quantity"/>
			<h1 class = "text-center" id="ex6SliderVal">8</h1>

			<input style="margin-top: 5%;" type="submit" class="btn btn-lg btn-info submit center-block" />
			<script>
			$("#ex8").slider({tooltip: 'hide'})
			$("#ex8").on("slide", function(slideEvt) {
			$("#ex6SliderVal").text(slideEvt.value);
			});
			</script>
			</div>

			<div class="col-md-2"></div>
	</div>
		
	

</div>

</form>

</div>

<%= render 'shared/footer' %>