config/routes.rb
Oncampuschef::Application.routes.draw do

  devise_for :customers, :controllers => { :omniauth_callbacks => "customers/omniauth_callbacks" }

  get "static_pages/why_us"
  get "static_pages/pricing"
  get "static_pages/what_we_do"
  get "static_pages/bbq"

  resources :charges, :except => [:show]
  resources :orders, :except => [:show]
  resources :barbecue_orders, :except => [:show]
  resources :barbecue_charges, :except => [:show]

 
  get "orders/vegetarian" => "orders#vegetarian"
  get "orders/food_picker" => "orders#food_picker"
  get "orders/test" => "orders#test"
  get "orders/test2" => "orders#test2"
  get "orders/quantity" => "orders#quantity"
  post "orders/new" => "orders#new"

  get "barbecue_orders/new"

  get "food_objects/menu"
 
  match '/chefs', to: 'static_pages#chefs', via: 'get'
  match '/profile', to: 'customers#show', via: 'get'
  match '/catering', to: 'catering_orders#new', via: 'get'

  get 'pages/index' => 'high_voltage/pages#show', id: 'index'

end

app/views/homestyle/group.html.erb
<% provide(:title, 'Home Style') %>
<%= render 'shared/header' %>

<div class="container" style="margin-top: 20px;">
	<div class="row">
		  <div class="col-sm-12">
            <legend><%= current_customer.customername %>:</legend>
        </div>
        <!-- panel preview -->
        <div class="col-sm-5">
            <h4>Fill out order:</h4>
            <div class="panel panel-default">
            	<%= form_for(@order) do |f| %>
				  <% if @order.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

				      <ul>
				      <% @order.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>
                <div class="panel-body form-horizontal payment-form">

                	<div class="form-group">
				   <p style="font-weight: bold" class="control-label">How many people are in your group?<p>
					    <%= f.select(:group, options_for_select(['2', '2'], ['3', '3'], ['4', '4']), { include_blank: true }, class: "btn btn-default dropdown-toggle form-control") %>
					    <span class="help-block"></span>
				  </div>
                    <div class="form-group">

                    	<div style="margin-left: 5%;">
	                    	<p>
						     Please enter the number of up to three food items, separated by commas, from the home style menu:
						 	</p>

						 	<ol>
						 	 <li>Chicken breast with brown rice</li>
						     <li>Tilapia with broccoli</li>
						     <li>Sweet potato with lemon chicken</li>
						     <li>Chicken salad with quinoa</li>
						     <li>Chicken breast with cous cous </li>
						     <li>Tilapia with brown rice</li>

						 	</ol>
					    </div>
					</br>
					     <div class="col-sm-12">
					     	<%= f.text_area :food_items, size: '50x3', class: 'form-control' %>
					 	</div>
					    <span class="help-block"></span>
					</div>
                    
                     <%# Added Bootstrap classes %>
					  <div class="actions">
					    <%= f.submit 'Submit', class: 'btn btn-info', name: 'homestyle_group_button' %>
					  </div>

                </div>
            </div>  
            <% end %>         
        </div>
	</div>
</div>

<%= render 'shared/footer' %>